import { GraphStateType, StreamEvent } from '../state';
import { AgentRunner } from '../runner';
import { ToolDefinition } from '../../../lib/ai-client';
import { runAgentStep } from '../services/agent-runtime';
import type { MissionTracker } from '../mission-tracker';
import { createMissionIntegrator } from '../mission-integrator';
import { loadPrompt } from '../../../lib/prompt-sync';
import { analyzeTask, decomposeTask } from '../task-decomposer';
import { getDependencyManager } from '../dependency-manager';
import { getSmartRefactorer } from '../smart-refactorer';

/**
 * AI Coding Assistant - Like Windsurf/Cursor for Kiro
 *
 * An intelligent coding assistant that understands context, provides smart suggestions,
 * and helps with development tasks through natural conversation and code analysis.
 *
 * Key Features:
 * - Context-aware code understanding and suggestions
 * - Intelligent code completion and refactoring
 * - Real-time error detection and fixes
 * - Smart dependency management
 * - Proactive code quality improvements
 * - Natural language to code translation
 */

interface CodeContext {
  currentFile?: string;
  selectedText?: string;
  cursorPosition?: { line: number; column: number };
  openFiles: string[];
  recentChanges: Array<{
    file: string;
    type: 'create' | 'modify' | 'delete';
    timestamp: number;
  }>;
  projectStructure: {
    framework?: string;
    language: string;
    dependencies: string[];
    testFramework?: string;
  };
}

interface CodeSuggestion {
  type: 'completion' | 'refactor' | 'fix' | 'optimize' | 'test';
  description: string;
  code?: string;
  file?: string;
  confidence: number;
  reasoning: string;
}

/**
 * Analyze the current codebase context to provide intelligent suggestions
 */
function analyzeCodeContext(state: GraphStateType): CodeContext {
  const dependencyManager = getDependencyManager();
  const allFiles = dependencyManager.getAllFiles();

  // Extract project information from actual codebase analysis
  // No hardcoded patterns - AI learns from actual code structure
  const projectStructure = {
    language: 'unknown', // Will be detected by AI from actual code
    dependencies: [],
    framework: undefined, // Will be detected by AI from actual code
    testFramework: undefined // Will be detected by AI from actual code
  };

  return {
    openFiles: allFiles.slice(0, 10), // Limit for performance
    recentChanges: [], // Would be populated from file system events
    projectStructure
  };
}

/**
 * Generate intelligent code suggestions based on context
 */
function generateCodeSuggestions(
  userInput: string,
  context: CodeContext,
  taskAnalysis: ReturnType<typeof analyzeTask>
): CodeSuggestion[] {
  const suggestions: CodeSuggestion[] = [];
  const dependencyManager = getDependencyManager();
  const refactorer = getSmartRefactorer();

  // Analyze for potential improvements in open files
  for (const file of context.openFiles.slice(0, 5)) {
    // Check for refactoring opportunities
    const refactorOps = refactorer.analyzeCodeArchitecture([file]);
    for (const op of refactorOps) {
      suggestions.push({
        type: 'refactor',
        description: op.description,
        file: op.file,
        confidence: op.impact === 'high' ? 0.9 : op.impact === 'medium' ? 0.7 : 0.5,
        reasoning: op.suggestion
      });
    }

    // Check for naming convention issues
    const namingIssues = refactorer.improveNamingConventions(file);
    for (const issue of namingIssues.slice(0, 3)) { // Limit suggestions
      suggestions.push({
        type: 'refactor',
        description: `Improve naming: ${issue.currentName} → ${issue.suggestedName}`,
        file: issue.file,
        confidence: 0.8,
        reasoning: issue.reason
      });
    }
  }

  // Detect circular dependencies
  const circularDeps = dependencyManager.detectCircularDependencies();
  for (const cycle of circularDeps.slice(0, 2)) {
    suggestions.push({
      type: 'fix',
      description: `Fix circular dependency: ${cycle.cycle.join(' → ')}`,
      confidence: cycle.severity === 'error' ? 0.95 : 0.8,
      reasoning: cycle.suggestion
    });
  }

  // Suggest tests if none exist
  const hasTests = context.openFiles.some(f =>
    f.includes('.test.') || f.includes('.spec.') || f.includes('__tests__')
  );

  if (!hasTests && (taskAnalysis.taskType === 'build' || taskAnalysis.taskType === 'coding')) {
    suggestions.push({
      type: 'test',
      description: 'Add unit tests for the implemented functionality',
      confidence: 0.9,
      reasoning: 'No test files detected. Adding tests will improve code reliability and maintainability.'
    });
  }

  // Framework-specific suggestions are now generated by AI
  // No hardcoded patterns - AI learns from actual codebase analysis
  // The CodebaseAnalyzer will detect frameworks from actual code structure

  // Sort by confidence and return top suggestions
  return suggestions
    .sort((a, b) => b.confidence - a.confidence)
    .slice(0, 5);
}

/**
 * Provide intelligent context-aware assistance
 */
function provideIntelligentAssistance(
  userInput: string,
  context: CodeContext,
  suggestions: CodeSuggestion[]
): string {
  let assistance = '';

  // Analyze user intent
  const isAsking = /\b(how|what|why|when|where|can|should|would)\b/i.test(userInput);
  const isRequesting = /\b(create|build|make|add|implement|write|generate)\b/i.test(userInput);
  const isFixing = /\b(fix|debug|error|issue|problem|bug)\b/i.test(userInput);

  if (isAsking) {
    assistance += '🤔 **Understanding your question...**\n\n';

    if (context.projectStructure.framework) {
      assistance += `I can see you're working with ${context.projectStructure.framework}. `;
    }

    assistance += 'Let me provide context-aware guidance based on your codebase.\n\n';
  }

  if (isRequesting) {
    assistance += '⚡ **Ready to implement...**\n\n';

    if (suggestions.length > 0) {
      assistance += '**Smart suggestions based on your codebase:**\n';
      for (const suggestion of suggestions.slice(0, 3)) {
        assistance += `• ${suggestion.description} (${Math.round(suggestion.confidence * 100)}% confidence)\n`;
      }
      assistance += '\n';
    }
  }

  if (isFixing) {
    assistance += '🔧 **Analyzing for issues...**\n\n';

    const fixSuggestions = suggestions.filter(s => s.type === 'fix');
    if (fixSuggestions.length > 0) {
      assistance += '**Issues detected:**\n';
      for (const fix of fixSuggestions) {
        assistance += `• ${fix.description}\n`;
      }
      assistance += '\n';
    }
  }

  // Add proactive suggestions
  const highConfidenceSuggestions = suggestions.filter(s => s.confidence > 0.8);
  if (highConfidenceSuggestions.length > 0 && !isAsking) {
    assistance += '💡 **Proactive suggestions:**\n';
    for (const suggestion of highConfidenceSuggestions.slice(0, 2)) {
      assistance += `• ${suggestion.description}\n  *${suggestion.reasoning}*\n\n`;
    }
  }

  return assistance;
}

export const createCodingSpecialistNode = (
  runner: AgentRunner,
  eventQueue?: StreamEvent[],
  missionTracker?: MissionTracker,
  toolDefs?: ToolDefinition[]
) => {
  const integrator = createMissionIntegrator(missionTracker);

  return async (state: GraphStateType): Promise<Partial<GraphStateType>> => {
    const tools = toolDefs || (runner as any)._buildToolDefinitions();

    // Detect if the user has already approved the plan
    const messages = state.messages || [];
    const planApproved = messages.some((m: any) => {
      const role = m.role || m._getType?.();
      const content = typeof m.content === 'string' ? m.content : JSON.stringify(m.content ?? '');
      return (role === 'user' || role === 'human') && content.includes('APPROVED');
    });

    // Detect task type from the user's original request
    const firstUserMsg = messages.find((m: any) => {
      const role = m.role || m._getType?.();
      return role === 'user' || role === 'human';
    });
    const userInput = firstUserMsg
      ? (typeof (firstUserMsg as any).content === 'string'
          ? (firstUserMsg as any).content
          : JSON.stringify((firstUserMsg as any).content))
      : '';

    const isBugFix = /\b(fix|bug|crash|error|broken|issue|not work|doesn't work|failing|regression)\b/i.test(userInput);

    // Build plan context from decomposed task
    const plan = state.decomposedTask;
    const planContext = plan
      ? `\n\nDECOMPOSED TASK:\nTitle: ${plan.title}\nSteps:\n${plan.steps.map((s: any) => `${s.id}: ${s.description} (Tool: ${s.tool})`).join('\n')}`
      : '';

    if (!planApproved) {
      // PHASE 1: Planning — instruct the agent to produce plan docs and ask for approval
      eventQueue?.push({ type: 'thought', content: '\n💻 Coding Specialist: Analysing request and preparing plan...' });

      const phaseHint = isBugFix
        ? `\n\n## CURRENT PHASE: PLANNING (Bug Fix)\nThe user has NOT yet approved a plan. You MUST:\n1. Write .everfern/plan/bugfix.md\n2. Write .everfern/plan/design.md\n3. Write .everfern/plan/tasks.md\n4. Call ask_user_question to present the plan for approval\nDO NOT write any application code yet.`
        : `\n\n## CURRENT PHASE: PLANNING (New Feature / Build)\nThe user has NOT yet approved a plan. You MUST:\n1. Write .everfern/plan/design.md\n2. Write .everfern/plan/tasks.md\n3. Call ask_user_question to present the plan for approval\nDO NOT write any application code yet.`;

      const systemPrompt = (loadPrompt('coding-specialist.md') || '') + planContext + phaseHint;

      const result = await integrator.wrapNode(
        'coding_specialist',
        () => runAgentStep(state, {
          runner,
          toolDefs: tools,
          eventQueue,
          nodeName: 'coding_specialist',
          systemPromptOverride: systemPrompt,
        }),
        'Preparing implementation plan'
      );

      return {
        ...result,
        returningFromSpecialist: 'coding_specialist',
        codingComplete: false // Still in planning
      };
    }

    // PHASE 2: Execution — plan approved, now implement
    eventQueue?.push({ type: 'thought', content: '\n💻 Coding Specialist: Plan approved — beginning implementation...' });

    const taskAnalysis = analyzeTask(userInput);
    const shouldDelegate = taskAnalysis.complexity === 'complex' || taskAnalysis.estimatedSteps > 5;

    const executionHint = `\n\n## CURRENT PHASE: EXECUTION\nThe user has approved the plan. Now implement it:\n1. Read .everfern/plan/tasks.md\n2. Execute each task in order\n3. Call getDiagnostics after every file write\n4. Fix errors before moving to the next task\n${shouldDelegate ? '5. Use spawn_agent with agent_type="coding-specialist" for complex independent subtasks\n' : ''}DO NOT re-present the plan or ask for approval again.
When all tasks in tasks.md are completed successfully, output 'MISSION_COMPLETE' to signal the end of implementation.`;

    const systemPrompt = (loadPrompt('coding-specialist.md') || '') + planContext + executionHint;

    const result = await integrator.wrapNode(
      'coding_specialist',
      () => runAgentStep(state, {
        runner,
        toolDefs: tools,
        eventQueue,
        nodeName: 'coding_specialist',
        systemPromptOverride: systemPrompt,
      }),
      'Writing Code & Implementing Features'
    );

    const scrubbedContent = (result.messages?.[0] as any)?.content || '';
    const isComplete = scrubbedContent.includes('MISSION_COMPLETE') || 
                       scrubbedContent.includes('TASK_FINISHED') ||
                       (result.pendingToolCalls?.length === 0 && scrubbedContent.length > 50);

    return {
      ...result,
      returningFromSpecialist: 'coding_specialist',
      codingComplete: isComplete
    };
  };
};
