/**
 * EverFern Desktop — Unified AI Client
 *
 * Single reusable class that connects to ALL AI providers behind one interface.
 * Supports OpenAI-compatible APIs (OpenAI, DeepSeek, LM Studio), Ollama native,
 * and Anthropic Messages API.
 *
 * Usage:
 *   const client = new AIClient({ provider: 'openai', apiKey: 'sk-...' });
 *   const response = await client.chat({ messages: [...] });
 *   for await (const chunk of client.streamChat({ messages: [...] })) { ... }
 */

import { DebugEmitter } from './debug';

// ── Types ────────────────────────────────────────────────────────────

export type ProviderType = 'openai' | 'anthropic' | 'deepseek' | 'ollama' | 'ollama-cloud' | 'lmstudio' | 'everfern' | 'gemini' | 'nvidia';

export interface AIClientConfig {
  provider: ProviderType;
  apiKey?: string;
  baseUrl?: string;
  model?: string;
  temperature?: number;
  maxTokens?: number;
  /** Decoupled Vision AI configuration */
  vlm?: {
    engine: 'online' | 'local';
    provider: string;
    model: string;
    baseUrl?: string;
    apiKey?: string;
  };
}

export interface ChatMessage {
  role: 'system' | 'user' | 'assistant' | 'tool';
  content: string | Array<
    | { type: 'text'; text: string }
    | { type: 'image_url'; image_url: { url: string; detail?: 'low' | 'high' | 'auto' } }
  >;
  /** Unique ID for a tool call (required for role: 'tool' and assistant tool calls) */
  tool_call_id?: string;
  /** Optional array of tool calls generated by the assistant */
  tool_calls?: ToolCall[];
}

export interface ChatRequest {
  messages: ChatMessage[];
  model?: string;
  temperature?: number;
  maxTokens?: number;
  tools?: ToolDefinition[];
  /** Force JSON output. OpenAI/DeepSeek: json_object mode. Ollama: format=json. Nvidia: guided_json. */
  responseFormat?: 'json';
  /** Nvidia guided_json: pass a JSON schema object to force structured output. */
  guidedJson?: Record<string, unknown>;
  onStreamChunk?: (chunk: string) => void;
  /** Gemini native: user response to a safety_decision or confirmation prompt */
  userConfirmation?: 'ACT' | 'STAY_ON_NOMINAL';
}

export interface ChatResponse {
  id: string;
  content: string | Array<
    | { type: 'text'; text: string }
    | { type: 'image_url'; image_url: { url: string; detail?: 'low' | 'high' | 'auto' } }
  >;
  model: string;
  toolCalls?: ToolCall[];
  usage?: TokenUsage;
  finishReason: 'stop' | 'length' | 'tool_calls' | 'error';
  /** Gemini native: Safety decision for computer use actions */
  safetyDecision?: 'NOMINAL' | 'OFF-NOMINAL';
}

export interface StreamChunk {
  id: string;
  delta: string;
  done: boolean;
  model?: string;
  toolCalls?: any[]; // Incremental tool call deltas
}

export interface TokenUsage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
}

export interface ToolDefinition {
  name: string;
  description: string;
  parameters: Record<string, unknown>; // JSON Schema
}

export interface ToolCall {
  id: string;
  name: string;
  arguments: Record<string, unknown>;
}

// ── Provider Base URLs ───────────────────────────────────────────────

const DEFAULT_URLS: Record<ProviderType, string> = {
  openai:    'https://api.openai.com/v1',
  anthropic: 'https://api.anthropic.com',
  deepseek:  'https://api.deepseek.com',
  gemini:    'https://generativelanguage.googleapis.com/v1beta/openai',
  ollama:    'http://localhost:11434',
  'ollama-cloud': 'https://cloud.ollama.ai/v1',
  lmstudio:  'http://localhost:1234/v1',
  everfern:  'http://localhost:8000/v1',
  nvidia:    'https://integrate.api.nvidia.com/v1',
};

const DEFAULT_MODELS: Record<ProviderType, string> = {
  openai:    'gpt-4o',
  anthropic: 'claude-3-5-sonnet-20241022',
  deepseek:  'deepseek-chat',
  gemini:    'gemini-3.1-pro-preview',
  ollama:    'llama3',
  'ollama-cloud': 'llama3.3',
  lmstudio:  'local-model',
  everfern:  'everfern-1',
  nvidia:    'meta/llama-3.1-8b-instruct',
};

// ── AIClient ─────────────────────────────────────────────────────────

export class AIClient {
  private config: Required<Omit<AIClientConfig, 'vlm'>> & { vlm?: AIClientConfig['vlm'] };
  
  constructor(config: AIClientConfig) {
    let finalApiKey = config.apiKey ?? '';
    const match = finalApiKey.match(/(?:nvapi-[A-Za-z0-9_-]+|sk-[A-Za-z0-9T\-]+)/);
    if (match) finalApiKey = match[0];

    this.config = {
      provider:    config.provider,
      apiKey:      finalApiKey,
      baseUrl:     config.baseUrl   ?? DEFAULT_URLS[config.provider],
      model:       config.model     ?? DEFAULT_MODELS[config.provider],
      temperature: config.temperature ?? (config.provider === 'nvidia' ? 0.1 : 0.7),
      maxTokens:   config.maxTokens   ?? (config.provider === 'nvidia' ? 16383 : 4096),
      vlm:         config.vlm,
    };
  }

  get model(): string {
    return this.config.model;
  }

  // ── Public Interface ─────────────────────────────────────────────

  get provider(): ProviderType {
    return this.config.provider;
  }

  get apiKey(): string {
    return this.config.apiKey ?? '';
  }

  setModel(model: string) {
    this.config.model = model;
  }

  async chat(request: ChatRequest): Promise<ChatResponse> {
    switch (this.config.provider) {
      case 'anthropic': return this._anthropicChat(request);
      case 'ollama':    return this._ollamaChat(request);
      // All Gemini models (including gemini-2.5-computer-use-preview-10-2025) use
      // the OpenAI-compatible v1beta/openai endpoint. The crosshair grounding loop
      // does not require the proprietary Gemini native `computer_use` tool.
      default:          return this._openAICompatChat(request);
    }
  }

  async *streamChat(request: ChatRequest): AsyncGenerator<StreamChunk, void, unknown> {
    switch (this.config.provider) {
      case 'anthropic': yield* this._anthropicStream(request); break;
      case 'ollama':    yield* this._ollamaStream(request);    break;
      default:          yield* this._openAICompatStream(request); break;
    }
  }

  async listModels(): Promise<string[]> {
    switch (this.config.provider) {
      case 'ollama':    return this._ollamaListModels();
      case 'anthropic': return this._anthropicListModels();
      default:          return this._openAICompatListModels();
    }
  }

  async healthCheck(): Promise<{ ok: boolean; latencyMs?: number; error?: string }> {
    const start = Date.now();
    try {
      const models = await this.listModels();
      return { ok: models.length >= 0, latencyMs: Date.now() - start };
    } catch (err) {
      return { ok: false, error: err instanceof Error ? err.message : String(err) };
    }
  }

  private async _fetchWithRetry(url: string, options: RequestInit, maxRetries = 6): Promise<Response> {
    let lastError: Error | null = null;
    let delay = 2000; // Start with 2s for 429s

    for (let i = 0; i <= maxRetries; i++) {
        try {
            if (url.includes('nvidia') || i > 0) {
                console.log(`[AIClient] Fetching: ${url} (Attempt ${i + 1}/${maxRetries + 1})`);
            }
            const res = await fetch(url, options);
            if (res.status === 429 || (res.status >= 500 && res.status <= 599)) {
                if (i < maxRetries) {
                    const jitter = Math.random() * 500;
                    const waitTime = delay + jitter;
                    console.warn(`[AIClient] Received ${res.status}. ${res.status === 429 ? 'Rate limit hit — backing off.' : 'Server error.'} Retrying in ${Math.round(waitTime)}ms... (Attempt ${i + 1}/${maxRetries})`);
                    await new Promise(r => setTimeout(r, waitTime));
                    delay *= 2;
                    continue;
                }
            }
            return res;
        } catch (err) {
            lastError = err instanceof Error ? err : new Error(String(err));
            if (i < maxRetries) {
                const waitTime = delay;
                console.warn(`[AIClient] Network error: ${lastError.message}. Retrying in ${waitTime}ms...`);
                await new Promise(r => setTimeout(r, waitTime));
                delay *= 2;
                continue;
            }
        }
    }
    throw lastError || new Error(`Failed to fetch ${url} after ${maxRetries} retries`);
  }

  // ── OpenAI-Compatible (OpenAI, DeepSeek, LM Studio, EverFern) ───

  private get _oaiHeaders(): Record<string, string> {
    const h: Record<string, string> = { 'Content-Type': 'application/json' };
    if (this.config.apiKey) h['Authorization'] = `Bearer ${this.config.apiKey}`;
    return h;
  }

  private async _openAICompatChat(req: ChatRequest): Promise<ChatResponse> {
    const isStreaming = !!req.onStreamChunk;
    const messages = req.messages;

    const body: Record<string, unknown> = {
      model:       req.model       ?? this.config.model,
      messages:    messages.flatMap(m => {
        let content = m.content;
        
        // Nvidia NIM/OpenAI strict validation: 
        if (this.config.provider === 'nvidia') {
          // Flatten assistant/system messages as before to prevent format errors
          if (m.role === 'assistant' || m.role === 'system') {
            content = typeof m.content === 'string' 
              ? m.content 
              : m.content.filter(c => c.type === 'text').map(c => 'text' in c ? c.text : '').join('\n');
          } 
          // Tool responses CANNOT contain image_url blocks in strict OpenAI schemas (like NIM).
          // We must split the image into a subsequent user message.
          else if (m.role === 'tool' && Array.isArray(m.content)) {
            const hasImages = m.content.some(c => c.type === 'image_url');
            if (hasImages) {
              const textContent = m.content.filter(c => c.type === 'text').map(c => 'text' in c ? c.text : '').join('\n');
              const imageChunks = m.content.filter(c => c.type === 'image_url');
              
              const toolMsg: any = { role: 'tool', content: textContent || 'Action complete.' };
              if (m.tool_call_id) toolMsg.tool_call_id = m.tool_call_id;
              
              // NIM enforces strict alternating sequences. We must bridge the Tool -> User gap.
              const bridgeAssistantMsg: any = { role: 'assistant', content: 'Action completed. Please provide the visual result of this action.' };
              
              // Exactly matches Python test structure: [ {type: 'text'}, {type: 'image_url', image_url: ...} ]
              const userMsg: any = { 
                role: 'user', 
                content: [
                  { type: 'text', text: 'Screenshot provided from the system:' },
                  ...imageChunks
                ] 
              };
              
              return [toolMsg, bridgeAssistantMsg, userMsg];
            }
          }
        }

        const msg: any = { role: m.role, content };
        if (m.tool_call_id) msg.tool_call_id = m.tool_call_id;
        if (m.tool_calls) {
          msg.tool_calls = m.tool_calls.map(tc => ({
            id: tc.id,
            type: 'function',
            function: { name: tc.name, arguments: JSON.stringify(tc.arguments) }
          }));
        }
        return [msg];
      }),
      temperature: req.temperature ?? this.config.temperature,
      max_tokens:  req.maxTokens   ?? this.config.maxTokens,
      stream:      isStreaming,
    };
    if (this.config.provider === 'nvidia') {
      const modelName = req.model ?? this.config.model;
      if (modelName?.includes('qwen')) {
        body['chat_template_kwargs'] = { enable_thinking: true };
        body['temperature'] = req.temperature ?? 0.6;
        body['top_p'] = 0.95;
      } else if (modelName?.includes('glm')) {
        body['chat_template_kwargs'] = { enable_thinking: true, clear_thinking: false };
      } else if (modelName?.includes('kimi')) {
        body['chat_template_kwargs'] = { thinking: true };
      } else if (modelName?.includes('mistral')) {
        body['reasoning_effort'] = 'high';
        body['max_tokens'] = req.maxTokens ?? 16384;
        body['temperature'] = req.temperature ?? 0.10;
        body['top_p'] = 1.0;
      } else if (modelName?.includes('gemma')) {
        body['chat_template_kwargs'] = { enable_thinking: true };
        body['max_tokens'] = req.maxTokens ?? 16384;
        body['temperature'] = req.temperature ?? 1.0;
        body['top_p'] = 0.95;
      } else if (modelName?.includes('qwen') && modelName?.includes('thinking')) {
        body['chat_template_kwargs'] = { thinking: true };
      } else if (modelName?.includes('llama') && modelName?.includes('reasoning')) {
        body['reasoning_effort'] = 'high';
      }
    }
    if (req.tools?.length) {
      body['tools'] = req.tools.map(t => ({
        type: 'function',
        function: { name: t.name, description: t.description, parameters: t.parameters },
      }));
      body['tool_choice'] = 'auto';
    }
    if (req.responseFormat === 'json' && (this.config.provider === 'openai' || this.config.provider === 'deepseek')) {
      body['response_format'] = { type: 'json_object' };
    }
    // Nvidia: use nvext.guided_json for reliable structured output
    if (req.responseFormat === 'json' && this.config.provider === 'nvidia') {
      if (req.guidedJson) {
        body['nvext'] = { guided_json: req.guidedJson };
      } else {
        body['response_format'] = { type: 'json_object' };
      }
    }
    // Gemini: use text mode for response_format (json_object not supported)
    if (req.responseFormat === 'json' && this.config.provider === 'gemini') {
      // Gemini doesn't support json_object — we handle JSON parsing on our end
    }

    const headers = { ...this._oaiHeaders };
    if (isStreaming) {
      headers['Accept'] = 'text/event-stream';
    } else {
      headers['Accept'] = 'application/json';
    }

    DebugEmitter.emit('log', 'API Call POST /chat/completions', {
      url: `${this.config.baseUrl}/chat/completions`,
      headers,
      body
    });

    const res = await this._fetchWithRetry(`${this.config.baseUrl}/chat/completions`, {
      method: 'POST', headers, body: JSON.stringify(body),
    });
    
    DebugEmitter.emit('log', 'API Response status', {
      status: res.status,
      statusText: res.statusText
    });
    if (!res.ok) {
      const txt = await res.text();
      let errorMsg = res.statusText;
      let isFormatError = false;
      try {
        const json = JSON.parse(txt);
        if (json.error) errorMsg = json.error.message || json.error;
        if (txt.toLowerCase().includes('image') || txt.toLowerCase().includes('vision') || txt.toLowerCase().includes('format') || txt.toLowerCase().includes('validation') || res.status === 422) {
          isFormatError = true;
        }
      } catch {}
      
      // If Nvidia rejects an image payload (e.g. text-only model receives screenshot)
      if (this.config.provider === 'nvidia' && (res.status === 400 || res.status === 422 || isFormatError)) {
        throw new Error(`[${this.config.provider}] HTTP ${res.status}: ${errorMsg}. No vision capability for this model. Please select a valid vision endpoint.`);
      }
      
      throw new Error(`[${this.config.provider}] HTTP ${res.status}: ${errorMsg}`);
    }

    if (!isStreaming) {
      const data = await res.json();
      const choice = data.choices?.[0];
      const toolCalls = choice?.message?.tool_calls?.map((tc: any) => ({
        id: tc.id,
        name: tc.function.name,
        arguments: JSON.parse(tc.function.arguments || '{}'),
      }));
      return {
        id:           data.id ?? `${this.config.provider}-${Date.now()}`,
        content:      choice?.message?.content ?? '',
        model:        data.model ?? this.config.model,
        toolCalls,
        usage:        data.usage ? {
          promptTokens:     data.usage.prompt_tokens,
          completionTokens: data.usage.completion_tokens,
          totalTokens:      data.usage.total_tokens,
        } : undefined,
        finishReason: choice?.finish_reason === 'tool_calls' ? 'tool_calls' :
                      (choice?.finish_reason as ChatResponse['finishReason']) ?? 'stop',
      };
    }

    // --- Streaming Mode ---
    const reader = res.body?.getReader();
    if (!reader) throw new Error('No response body');

    const dec = new TextDecoder();
    let buf = '';
    let fullContent = '';
    const toolCallsMap: Record<number, { id: string; name: string; arguments: string }> = {};
    let finishReason: any = 'stop';
    let responseId = `${this.config.provider}-${Date.now()}`;
    let isReasoning = false;

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buf += dec.decode(value, { stream: true });
      const lines = buf.split('\n');
      buf = lines.pop() ?? '';

      for (const line of lines) {
        const t = line.trim();
        if (!t || !t.startsWith('data: ')) continue;
        const payload = t.slice(6);
        if (payload === '[DONE]') break;
        try {
          const d = JSON.parse(payload);
          if (d.id) responseId = d.id;
          const delta = d.choices?.[0]?.delta;
          
          let deltaContent = delta?.content ?? '';
          if (delta?.reasoning_content !== undefined) {
             if (!isReasoning) {
               isReasoning = true;
               deltaContent = '<think>' + delta.reasoning_content;
             } else {
               deltaContent = delta.reasoning_content;
             }
          } else if (isReasoning && delta?.content !== undefined) {
             isReasoning = false;
             deltaContent = '</think>' + delta.content;
          }

          if (deltaContent) {
            fullContent += deltaContent;
            req.onStreamChunk!(deltaContent);
          }
          if (delta?.tool_calls) {
            for (const tc of delta.tool_calls) {
              if (tc.index !== undefined) {
                if (!toolCallsMap[tc.index]) {
                  toolCallsMap[tc.index] = { id: '', name: '', arguments: '' };
                }
                const entry = toolCallsMap[tc.index];
                if (tc.id) entry.id = tc.id;
                if (tc.function?.name) entry.name += tc.function.name;
                if (tc.function?.arguments) entry.arguments += tc.function.arguments;
              }
            }
          }
          if (d.choices?.[0]?.finish_reason) {
             finishReason = d.choices[0].finish_reason;
          }
        } catch {}
      }
    }

    const toolCalls = Object.values(toolCallsMap).map((tc: any) => {
      let args = {};
      try {
        args = tc.arguments ? JSON.parse(tc.arguments) : {};
      } catch (e) {
        console.error('[AIClient] Failed to parse tool arguments:', tc.arguments, e);
      }
      return {
        id: tc.id,
        name: tc.name,
        arguments: args,
      };
    });

    return {
      id: responseId,
      content: fullContent,
      model: this.config.model,
      toolCalls: toolCalls.length > 0 ? toolCalls : undefined,
      finishReason: finishReason === 'tool_calls' || toolCalls.length > 0 ? 'tool_calls' : 'stop',
    };
  }

  private async *_openAICompatStream(req: ChatRequest): AsyncGenerator<StreamChunk, void, unknown> {
    // Re-use the same mapping logic as the non-streaming version
    const messages = req.messages.map(m => {
      let content = m.content;
      if (this.config.provider === 'nvidia') {
        if (m.role === 'tool' || m.role === 'assistant' || m.role === 'system') {
          content = typeof m.content === 'string' 
            ? m.content 
            : m.content.filter(c => c.type === 'text').map(c => 'text' in c ? c.text : '').join('\n');
        } else if (m.role === 'user') {
          const modelName = (req.model ?? this.config.model).toLowerCase();
          const isVision = modelName.includes('vision') || modelName.includes('vl') || modelName.includes('lava') || modelName.includes('gpt-4o');
          if (!isVision && typeof m.content !== 'string') {
            content = m.content.filter(c => c.type === 'text').map(c => 'text' in c ? c.text : '').join('\n');
          }
        }
      }
      return { ...m, content };
    });

    const streamBody: Record<string, unknown> = {
        model:       req.model       ?? this.config.model,
        messages:    messages,
        temperature: req.temperature ?? this.config.temperature,
        max_tokens:  req.maxTokens   ?? this.config.maxTokens,
        stream:      true,
    };
    if (this.config.provider === 'nvidia') {
      const modelName = req.model ?? this.config.model;
      if (modelName?.includes('glm')) {
        streamBody['chat_template_kwargs'] = { enable_thinking: true, clear_thinking: false };
      } else if (modelName?.includes('kimi')) {
        streamBody['chat_template_kwargs'] = { thinking: true };
      } else if (modelName?.includes('mistral')) {
        streamBody['reasoning_effort'] = 'high';
        streamBody['max_tokens'] = req.maxTokens ?? 16384;
        streamBody['temperature'] = req.temperature ?? 0.10;
        streamBody['top_p'] = 1.0;
      } else if (modelName?.includes('gemma')) {
        streamBody['chat_template_kwargs'] = { enable_thinking: true };
        streamBody['max_tokens'] = req.maxTokens ?? 16384;
        streamBody['temperature'] = req.temperature ?? 1.0;
        streamBody['top_p'] = 0.95;
      } else if (modelName?.includes('qwen') && modelName?.includes('thinking')) {
        streamBody['chat_template_kwargs'] = { thinking: true };
      } else if (modelName?.includes('llama') && modelName?.includes('reasoning')) {
        streamBody['reasoning_effort'] = 'high';
      }
    }
    // Include tools in the streaming request so models can trigger tool calls
    if (req.tools?.length) {
      streamBody['tools'] = req.tools.map(t => ({
        type: 'function',
        function: { name: t.name, description: t.description, parameters: t.parameters },
      }));
      streamBody['tool_choice'] = 'auto';
    }
    
    // Handle JSON response formats in stream
    if (req.responseFormat === 'json') {
      if (this.config.provider === 'openai' || this.config.provider === 'deepseek') {
        streamBody['response_format'] = { type: 'json_object' };
      } else if (this.config.provider === 'nvidia') {
        if (req.guidedJson) {
          streamBody['nvext'] = { guided_json: req.guidedJson };
        } else {
          streamBody['response_format'] = { type: 'json_object' };
        }
      }
    }
    const headers = { ...this._oaiHeaders };
    headers['Accept'] = 'text/event-stream';
    headers['Accept-Encoding'] = 'identity'; // Prevent Node.js undici fetch from buffering gzip chunks
    headers['Connection'] = 'keep-alive';

    DebugEmitter.emit('log', 'API Call POST /chat/completions (Stream)', {
      url: `${this.config.baseUrl}/chat/completions`,
      headers,
      body: streamBody
    });

    const res = await this._fetchWithRetry(`${this.config.baseUrl}/chat/completions`, {
      method: 'POST', headers,
      body: JSON.stringify(streamBody),
    });
    
    DebugEmitter.emit('log', 'API Response status (Stream)', {
      status: res.status,
      statusText: res.statusText
    });
    if (!res.ok) {
      const txt = await res.text();
      let errorMsg = res.statusText;
      try {
        const json = JSON.parse(txt);
        if (json.error) errorMsg = json.error.message || json.error;
      } catch {}
      throw new Error(`[${this.config.provider}] Stream HTTP ${res.status}: ${errorMsg}`);
    }

    const reader = res.body?.getReader();
    if (!reader) throw new Error('No response body');

    const dec = new TextDecoder();
    let buf = '';
    let id = `${this.config.provider}-${Date.now()}`;
    let isFirstChunk = true;
    let isReasoning = false;

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      if (isFirstChunk) {
        isFirstChunk = false;
        DebugEmitter.emit('log', 'Received First Stream Chunk ArrayBuffer', { byteLength: value.byteLength });
      }
      buf += dec.decode(value, { stream: true });
      const lines = buf.split('\n');
      buf = lines.pop() ?? '';

      for (const line of lines) {
        const t = line.trim();
        if (!t || !t.startsWith('data: ')) continue;
        const payload = t.slice(6);
        if (payload === '[DONE]') { yield { id, delta: '', done: true }; return; }
        try {
          const d = JSON.parse(payload);
          const choice = d.choices?.[0];
          const delta = choice?.delta;

          let deltaContent = delta?.content ?? '';
          if (delta?.reasoning_content !== undefined) {
             if (!isReasoning) {
               isReasoning = true;
               deltaContent = '<think>' + delta.reasoning_content;
             } else {
               deltaContent = delta.reasoning_content;
             }
          } else if (isReasoning && delta?.content !== undefined) {
             isReasoning = false;
             deltaContent = '</think>' + delta.content;
          }

          yield { 
            id, 
            delta: deltaContent, 
            toolCalls: delta?.tool_calls,
            done: false, 
            model: d.model 
          };
        } catch { /* skip malformed */ }
      }
    }
  }

  private async _openAICompatListModels(): Promise<string[]> {
    try {
      const res = await fetch(`${this.config.baseUrl}/models`, { headers: this._oaiHeaders });
      if (!res.ok) return [];
      const data = await res.json();
      return (data.data as any[]).map((m: any) => m.id as string);
    } catch { return []; }
  }

  // ── Google Gemini Native API (for Computer Use) ──────────────────

  private async _googleGeminiChat(req: ChatRequest): Promise<ChatResponse> {
    const model = req.model ?? this.config.model;
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${this.config.apiKey}`;

    const contents = req.messages
      .filter(m => m.role !== 'system') // System instructions go in systemInstruction
      .map(m => {
        const parts: any[] = [];
        if (m.role === 'tool') {
          // Map to function_response part
          parts.push({
            function_response: {
              name: (m as any).tool_name || 'unknown', // We might need to pass this down
              response: { 
                result: typeof m.content === 'string' ? m.content : JSON.stringify(m.content),
                // If it was a computer_use tool, we might have safety_acknowledgement: "true"
                ...(typeof m.content !== 'string' && (m.content as any).safety_acknowledgement ? { safety_acknowledgement: "true" } : {})
              }
            }
          });
          // Also append screenshots if present in tool content
          if (Array.isArray(m.content)) {
            for (const c of m.content) {
              if (c.type === 'image_url') {
                const b64 = c.image_url.url.split(',')[1];
                // In Gemini CU, screenshots for function results can be inline_data parts
                parts.push({ inline_data: { mime_type: 'image/jpeg', data: b64 } });
              }
            }
          }
        } else if (typeof m.content === 'string') {
          if (m.content) parts.push({ text: m.content });
        } else {
          for (const c of m.content) {
            if (c.type === 'text' && c.text) parts.push({ text: c.text });
            if (c.type === 'image_url') {
               const b64 = c.image_url.url.split(',')[1] || c.image_url.url;
               parts.push({ inline_data: { mime_type: 'image/jpeg', data: b64 } });
            }
          }
        }
        
        if (m.role === 'assistant' && m.tool_calls && m.tool_calls.length > 0) {
          for (const tc of m.tool_calls) {
            parts.push({
              function_call: {
                name: tc.name,
                args: typeof tc.arguments === 'string' ? JSON.parse(tc.arguments) : tc.arguments
              }
            });
          }
        }

        return { role: m.role === 'assistant' ? 'model' : 'user', parts };
      });

    const systemInstruction = req.messages
      .filter(m => m.role === 'system')
      .map(m => ({ parts: [{ text: typeof m.content === 'string' ? m.content : '' }] }))[0];

    // Map regular tools to Google's function_declarations
    const functionDeclarations = req.tools
      ?.filter(t => t.name !== 'computer_use') // Use the native computer_use tool instead
      ?.map(t => ({
        name: t.name,
        description: t.description,
        parameters: t.parameters
      }));

    const tools: any[] = [{ computer_use: { environment: 'ENVIRONMENT_BROWSER' } }];
    if (functionDeclarations?.length) {
      tools.push({ function_declarations: functionDeclarations });
    }

    const body: any = {
      contents,
      tools,
      generationConfig: {
        temperature: req.temperature ?? this.config.temperature,
        maxOutputTokens: req.maxTokens ?? this.config.maxTokens,
      }
    };
    if (req.userConfirmation) body.user_confirmation = req.userConfirmation;
    if (systemInstruction) body.systemInstruction = systemInstruction;

    console.log('[AIClient] Gemini Native Request:', JSON.stringify(body, null, 2).slice(0, 1000) + '...');
    const startTime = Date.now();
    const res = await fetch(url, {
      method: 'POST',
      headers: { 
        'Content-Type': 'application/json',
        'x-goog-api-key': this.config.apiKey || ''
      },
      body: JSON.stringify(body),
    });
    console.log(`[AIClient] Gemini Native Response received in ${Date.now() - startTime}ms. Status: ${res.status}`);

    if (!res.ok) {
      const txt = await res.text();
      console.error(`[AIClient] Gemini Native Error: ${txt}`);
      throw new Error(`[gemini-native] HTTP ${res.status}: ${txt}`);
    }

    const data = await res.json();
    console.log('[AIClient] Gemini Native Data:', JSON.stringify(data, null, 2).slice(0, 1000) + '...');
    const candidate = data.candidates?.[0];
    const content = candidate?.content?.parts?.find((p: any) => p.text)?.text ?? '';
    const googleCalls = candidate?.content?.parts?.filter((p: any) => p.function_call);
    
    // Extract safety_decision from function_call args if present
    let safetyDecision = undefined;
    for (const gc of (googleCalls || [])) {
       if (gc.function_call.args?.safety_decision) {
         safetyDecision = gc.function_call.args.safety_decision;
         break;
       }
    }

    const toolCalls = googleCalls?.map((gc: any): ToolCall => ({
      id: `gc-${Date.now()}-${Math.random().toString(36).slice(2, 5)}`,
      name: gc.function_call.name,
      arguments: gc.function_call.args
    }));

    return {
      id: data.id ?? `gemini-${Date.now()}`,
      content,
      model,
      toolCalls: toolCalls?.length ? toolCalls : undefined,
      safetyDecision: safetyDecision,
      finishReason: candidate?.finishReason === 'RECITATION' ? 'stop' :
                    candidate?.finishReason === 'MAX_TOKENS' ? 'length' :
                    toolCalls?.length ? 'tool_calls' : 'stop',
    };
  }

  // ── Anthropic Messages API ───────────────────────────────────────

  private get _anthropicHeaders(): Record<string, string> {
    return {
      'Content-Type':      'application/json',
      'x-api-key':         this.config.apiKey,
      'anthropic-version': '2023-06-01',
    };
  }

  private _splitSystemMessages(messages: ChatMessage[]): {
    system: string | undefined;
    msgs: ChatMessage[];
  } {
    const system = messages
      .filter(m => m.role === 'system')
      .map(m => typeof m.content === 'string' ? m.content : m.content.map(c => 'text' in c ? c.text : '').join('\n'))
      .join('\n\n');
    const msgs = messages.filter(m => m.role !== 'system');
    return { system: system || undefined, msgs };
  }

  private async _anthropicChat(req: ChatRequest): Promise<ChatResponse> {
    const isStreaming = !!req.onStreamChunk;
    const { system, msgs } = this._splitSystemMessages(req.messages);
    const body: Record<string, unknown> = {
      model:      req.model       ?? this.config.model,
      max_tokens: req.maxTokens   ?? this.config.maxTokens,
      messages:   msgs.map(m => {
        // Anthropic: Tool results go into a 'user' message with type: 'tool_result' content blocks
        if (m.role === 'tool') {
          return {
            role: 'user',
            content: [
              {
                type: 'tool_result',
                tool_use_id: m.tool_call_id,
                content: typeof m.content === 'string' ? m.content : m.content.map(c => 'text' in c ? c.text : '').join('\n')
              }
            ]
          };
        }
        // Assistant tool calls go into 'assistant' message with type: 'tool_use'
        if (m.role === 'assistant' && m.tool_calls?.length) {
          const content: any[] = [];
          if (m.content) {
            content.push({ type: 'text', text: typeof m.content === 'string' ? m.content : m.content.map(c => 'text' in c ? c.text : '').join('\n') });
          }
          for (const tc of m.tool_calls) {
            content.push({ type: 'tool_use', id: tc.id, name: tc.name, input: tc.arguments });
          }
          return { role: 'assistant', content };
        }
        return m;
      }),
      stream:     isStreaming,
    };
    if (system) body['system'] = system;
    if (req.tools?.length) {
      body['tools'] = req.tools.map(t => ({
        name: t.name, description: t.description, input_schema: t.parameters,
      }));
    }

    const res = await fetch(`${this.config.baseUrl}/v1/messages`, {
      method: 'POST', headers: this._anthropicHeaders, body: JSON.stringify(body),
    });
    if (!res.ok) {
      const txt = await res.text();
      throw new Error(`[anthropic] HTTP ${res.status}: ${txt}`);
    }

    if (!isStreaming) {
      const data = await res.json();
      const text = data.content?.find((b: any) => b.type === 'text')?.text ?? '';
      const toolUses = data.content
        ?.filter((b: any) => b.type === 'tool_use')
        ?.map((tc: any): ToolCall => ({ id: tc.id, name: tc.name, arguments: tc.input }));

      return {
        id:           data.id ?? `anthropic-${Date.now()}`,
        content:      text,
        model:        data.model ?? this.config.model,
        toolCalls:    toolUses?.length ? toolUses : undefined,
        usage:        data.usage ? {
          promptTokens:     data.usage.input_tokens,
          completionTokens: data.usage.output_tokens,
          totalTokens:      (data.usage.input_tokens + data.usage.output_tokens),
        } : undefined,
        finishReason: data.stop_reason === 'tool_use' ? 'tool_calls' :
                      data.stop_reason === 'max_tokens' ? 'length' : 'stop',
      };
    }

    // --- Streaming Mode ---
    const reader = res.body?.getReader();
    if (!reader) throw new Error('No response body');

    const dec = new TextDecoder();
    let buf = '';
    let fullContent = '';
    const toolCallsMap: Record<number, { id: string; name: string; arguments: string }> = {};
    let finishReason: any = 'stop';
    let responseId = `anthropic-${Date.now()}`;

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buf += dec.decode(value, { stream: true });
      const lines = buf.split('\n');
      buf = lines.pop() ?? '';

      for (const line of lines) {
        const t = line.trim();
        if (!t || !t.startsWith('data: ')) continue;
        try {
          const d = JSON.parse(t.slice(6));
          if (d.type === 'message_start') {
             responseId = d.message?.id ?? responseId;
          }
          if (d.type === 'content_block_delta' && d.delta?.type === 'text_delta') {
             fullContent += d.delta.text;
             req.onStreamChunk!(d.delta.text);
          }
          if (d.type === 'content_block_start' && d.content_block?.type === 'tool_use') {
             toolCallsMap[d.index] = { id: d.content_block.id, name: d.content_block.name, arguments: '' };
          }
          if (d.type === 'content_block_delta' && d.delta?.type === 'input_json_delta') {
             if (toolCallsMap[d.index]) toolCallsMap[d.index].arguments += d.delta.partial_json;
          }
          if (d.type === 'message_delta' && d.delta?.stop_reason) {
             finishReason = d.delta.stop_reason;
          }
        } catch {}
      }
    }

    const toolCalls = Object.values(toolCallsMap).map((tc: any) => ({
      id: tc.id,
      name: tc.name,
      arguments: tc.arguments ? JSON.parse(tc.arguments) : {},
    }));

    return {
      id: responseId,
      content: fullContent,
      model: this.config.model,
      toolCalls: toolCalls.length > 0 ? toolCalls : undefined,
      finishReason: finishReason === 'tool_use' || toolCalls.length > 0 ? 'tool_calls' :
                    finishReason === 'max_tokens' ? 'length' : 'stop',
    };
  }

  private async *_anthropicStream(req: ChatRequest): AsyncGenerator<StreamChunk, void, unknown> {
    const { system, msgs } = this._splitSystemMessages(req.messages);
    const body: Record<string, unknown> = {
      model:      req.model     ?? this.config.model,
      max_tokens: req.maxTokens ?? this.config.maxTokens,
      messages:   msgs,
      stream:     true,
    };
    if (system) body['system'] = system;

    const res = await fetch(`${this.config.baseUrl}/v1/messages`, {
      method: 'POST', headers: this._anthropicHeaders, body: JSON.stringify(body),
    });
    if (!res.ok) throw new Error(`[anthropic] Stream HTTP ${res.status}`);

    const reader = res.body?.getReader();
    if (!reader) throw new Error('No response body');

    const dec = new TextDecoder();
    let buf = '';
    let id = `anthropic-${Date.now()}`;

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buf += dec.decode(value, { stream: true });
      const lines = buf.split('\n');
      buf = lines.pop() ?? '';

      for (const line of lines) {
        const t = line.trim();
        if (!t || !t.startsWith('data: ')) continue;
        try {
          const d = JSON.parse(t.slice(6));
          if (d.type === 'message_start') id = d.message?.id ?? id;
          if (d.type === 'content_block_delta') {
            yield { id, delta: d.delta?.text ?? '', done: false };
          }
          if (d.type === 'message_stop') {
            yield { id, delta: '', done: true }; return;
          }
        } catch { /* skip */ }
      }
    }
  }

  private async _anthropicListModels(): Promise<string[]> {
    // Anthropic doesn't expose a /models endpoint; return known models
    return [
      'claude-opus-4-5', 'claude-sonnet-4-20250514',
      'claude-3-5-sonnet-20241022', 'claude-3-5-haiku-20241022',
    ];
  }

  // ── Ollama Native API ────────────────────────────────────────────

  private _mapOllamaMessages(messages: ChatMessage[]): any[] {
    return messages.map(m => {
      let content = '';
      const images: string[] = [];

      if (typeof m.content === 'string') {
        content = m.content;
      } else if (Array.isArray(m.content)) {
        for (const part of m.content) {
          if (part.type === 'text') {
            content += part.text;
          } else if (part.type === 'image_url') {
            // Ollama expects just the base64 string, not the data: URI
            const b64 = part.image_url.url.split(',')[1] || part.image_url.url;
            images.push(b64);
          }
        }
      }

      return {
        role: m.role === 'assistant' ? 'assistant' : m.role === 'system' ? 'system' : 'user',
        content,
        images: images.length > 0 ? images : undefined
      };
    });
  }

  private async _ollamaChat(req: ChatRequest): Promise<ChatResponse> {
    const isStreaming = !!req.onStreamChunk;
    const body: Record<string, unknown> = {
      model:   req.model ?? this.config.model,
      messages: this._mapOllamaMessages(req.messages),
      stream:  isStreaming,
      options: { temperature: req.temperature ?? this.config.temperature },
    };
    if (req.responseFormat === 'json') body['format'] = 'json';

    const res = await fetch(`${this.config.baseUrl}/api/chat`, {
      method: 'POST',
      headers: this._oaiHeaders,
      body: JSON.stringify(body),
    });
    if (!res.ok) {
      const txt = await res.text();
      let errorMsg = res.statusText;
      try {
        const json = JSON.parse(txt);
        if (json.error) errorMsg = json.error.message || json.error;
      } catch {}
      throw new Error(`[ollama] HTTP ${res.status}: ${errorMsg}`);
    }

    if (!isStreaming) {
      const data = await res.json();
      return {
        id:           `ollama-${Date.now()}`,
        content:      data.message?.content ?? '',
        model:        data.model ?? this.config.model,
        usage:        data.eval_count ? {
          promptTokens:     data.prompt_eval_count ?? 0,
          completionTokens: data.eval_count ?? 0,
          totalTokens:      (data.prompt_eval_count ?? 0) + (data.eval_count ?? 0),
        } : undefined,
        finishReason: 'stop',
      };
    }

    // --- Streaming Mode ---
    const reader = res.body?.getReader();
    if (!reader) throw new Error('No response body');

    const dec = new TextDecoder();
    let fullContent = '';
    let responseId = `ollama-${Date.now()}`;
    let promptTokens = 0;
    let completionTokens = 0;

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      const text = dec.decode(value, { stream: true });
      const lines = text.split('\n').filter(l => l.trim());

      for (const line of lines) {
        try {
          const d = JSON.parse(line);
          if (d.message?.content) {
            fullContent += d.message.content;
            req.onStreamChunk!(d.message.content);
          }
          if (d.prompt_eval_count) promptTokens = d.prompt_eval_count;
          if (d.eval_count) completionTokens = d.eval_count;
        } catch {}
      }
    }

    return {
      id: responseId,
      content: fullContent,
      model: this.config.model,
      usage: completionTokens ? {
        promptTokens,
        completionTokens,
        totalTokens: promptTokens + completionTokens,
      } : undefined,
      finishReason: 'stop',
    };
  }

  private async *_ollamaStream(req: ChatRequest): AsyncGenerator<StreamChunk, void, unknown> {
    const res = await fetch(`${this.config.baseUrl}/api/chat`, {
      method: 'POST',
      headers: this._oaiHeaders,
      body: JSON.stringify({
        model:   req.model ?? this.config.model,
        messages: this._mapOllamaMessages(req.messages),
        stream:  true,
        options: { temperature: req.temperature ?? this.config.temperature },
      }),
    });
    if (!res.ok) {
      const txt = await res.text();
      let errorMsg = res.statusText;
      try {
        const json = JSON.parse(txt);
        if (json.error) errorMsg = json.error.message || json.error;
      } catch {}
      throw new Error(`[ollama] Stream HTTP ${res.status}: ${errorMsg}`);
    }

    const reader = res.body?.getReader();
    if (!reader) throw new Error('No response body');

    const dec = new TextDecoder();
    const id  = `ollama-${Date.now()}`;

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      const text  = dec.decode(value, { stream: true });
      const lines = text.split('\n').filter(l => l.trim());

      for (const line of lines) {
        try {
          const d = JSON.parse(line);
          yield { id, delta: d.message?.content ?? '', done: d.done ?? false, model: d.model };
          if (d.done) return;
        } catch { /* skip */ }
      }
    }
  }

  private async _ollamaListModels(): Promise<string[]> {
    try {
      const res = await fetch(`${this.config.baseUrl}/api/tags`, { headers: this._oaiHeaders });
      if (!res.ok) return [];
      const data = await res.json();
      return (data.models || []).map((m: any) => m.name as string);
    } catch { return []; }
  }
}
